### ISSUE TITLE
Переклад governance.md з io.js

### ISSUE THREAD

**Issue by sejoker** [iojs/iojs-uk#17]
https://github.com/iojs/website/issues/198

**Comment by sudodoki** [comment]
Розпочато у https://github.com/iojs/iojs-uk/pull/22

**Comment by vladmiller** [comment]
@eko24 я закончил с переводом недостающих параграфов. Обратил внимание, что в твоем переводе присутствуют некоторые ошибки\опечатки и в моем переводе их в три раза больше. Я файл отправил на исправление людям которые на Украинском пишут лучше чем на скале:) чуть позже залью. Ты меня потом перепроверь пожалуйста.

**Comment by eko24** [comment]
@vladmiller окей, я чуть позже вычитаю это дело и закомичусь.

**Comment by ghaiklor** [comment]
Уже переведено.
