### ISSUE TITLE
Make ua.iojs.org

### ISSUE THREAD

**Issue by ghaiklor** [iojs/iojs-uk#31]
Make gh-pages branch, where will be located iojs in Ukrainian. And don't forgot about CNAME.

**Comment by sejoker** [comment]
Let's discuss it in the chat, I don't think it is a good idea.

**Comment by ghaiklor** [comment]
@sejoker ok, so here our main point for now. Make ua.iojs.org kinda our personal blog for team. At ua.iojs.org we can post iojs weekly, information for translators, our team, etc... What do you think ?

**Comment by sejoker** [comment]
That makes sense, I like the idea

**Comment by ghaiklor** [comment]
I'd created [ua.iojs.org](http://ua.iojs.org), so this issue can be closed.
