### ISSUE TITLE
using UA instead of UK 

### ISSUE THREAD

**Issue by sejoker** [iojs/iojs-uk#5]
If we plan to communicate via social media it makes sense using ua for ukrainian instead of uk, which is United Kingdom. I would suggest sticking to iojs-ua for ukrainian localization.

**Comment by AntouanK** [comment]
Yeah, it was very confusing to me also when I saw uk.

Nevertheless, I made already an account on twitter and gmail for iojs_uk.
If you are going to need them, drop me an email so I can hand over the credentials.

**Comment by sejoker** [comment]
I cleared this up with the help of @listochkin and @mikeal. We are using language code which is uk for Ukrainian instead of localization (UA)
