### ISSUE TITLE
Переклад останніх новин io.js за лютий 2015

### ISSUE THREAD

**Issue by sejoker** [iojs/iojs-uk#6]
- переклад статті українскою https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4
- запостити на dou.ua (українскою чи російською), twitter.

**Comment by sejoker** [comment]
Переклад зроблено, але постити на форумі доу це велике лихо, не бачу сенсу.

**Comment by sudodoki** [comment]
Мені цікаво, що з цього приводу може сказати @programulya

**Comment by programulya** [comment]
Можна спробувати на ДОУ, але треба бути готовим "підверстати" під ДОУ (займає багато часу) :)
