### ISSUE TITLE
Setting up environment for ua.iojs.org

### ISSUE THREAD

**Issue by ghaiklor** [iojs/iojs-uk#71]
I've start working with our ua.iojs.org website and here my primary points for now:
- Choose platform: [List of all static generators](https://www.staticgen.com) but I think it will be hexo or harp;
- Choose site structure. My proposal for quick start is - team, how to help and blog;
- Configure git workflow and dev/prod environments. The main problem here, that we need keep source and generated public files in different branches, but I don't want it. If it's possible, need to find out the way how we can store, for instance, hexo source files and generated files in one branch, but in different folders. Can we proxy gh-pages url to `dist` folder or some else ?

**Comment by eko24** [comment]
For dev enviroment I can recomend [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp) + Jade.

**Comment by ghaiklor** [comment]
@sejoker and @eko24 Finally I decide to choose [Jekyll](http://jekyllrb.com) which goes with GitHub Pages right from the box. Just test it out and don't see any issues with posts generation, cloning branches, etc... Hope that today I'll finish structure and our first layouts and posts :beers:
