### ISSUE TITLE
Додати приватну інформацію до ua.iojs.org

### ISSUE THREAD

**Issue by sejoker** [iojs/iojs-uk#73]
Євген Сафронов
Розробник, ентузіаст nodeschool та nodebots. Захоплююсь роботами. Живу та працюю в Берліні.
twitter: @sejoker
github: github.com/sejoker
avatar:  https://www.dropbox.com/s/81vr99odydxa3km/safronov_avatar.JPG?dl=0

**Comment by ghaiklor** [comment]
@sejoker а у тебя есть на аватар на граватаре?

**Comment by sejoker** [comment]
https://en.gravatar.com/site/check/sejoker@gmail.com

**Comment by ghaiklor** [comment]
@sejoker добавил :+1:
