### ISSUE TITLE
Requests to join nodejs-uk

### ISSUE THREAD

**Issue by Trott** [iojs/iojs-uk#82]
There are currently two individuals who have requested joining @nodejs/nodejs-uk. 

Unfortunately, no one already in @nodejs/nodejs-uk is a maintainer so no one in the group can approve or deny the requests.

So, two questions:
- Do you want me to do anything with the pending requests? Just accept them?
- Might there be one or more people already in @nodejs/nodejs-uk who can be appointed maintainer so the group can handle requests? The group could put together a formal review process (if desired) or whatever.

**Comment by denysdovhan** [comment]
I would like to translate node's docs to Ukrainian, but currently I'm working on [Understanding ES6](https://github.com/denysdovhan/understandinges6ua) book. I think I can take some part of work later. Moreover, I already have a team of Ukrainian philologists and they can make a good professional review.

**Comment by denysdovhan** [comment]
Now, I think it's better to wait for @listochkin, @ghaiklor's decision. Guys, will does anybody working on the translation now?

**Comment by ghaiklor** [comment]
@denysdovhan no, we faced issues with a translators, since we are more close to Russian language then Ukrainian. I'll be glad to continue work on that, if you have a team.

@Trott 

> Might there be one or more people already in @nodejs/nodejs-uk who can be appointed maintainer so the group can handle requests?

I thought we have one 😟 @listochkin 
I know @denysdovhan personally, so he can be in charge of it. In case, I can handle it as well.

**Comment by Trott** [comment]
I made @ghaiklor team maintainer based on conversation here and raw commit numbers. Maintainer role means you can approve/deny requests to join the team and probably a few other things (like assign other individuals to be maintainers too).

@ghaiklor: You can see the pending requests to join the team at https://github.com/orgs/nodejs/teams/nodejs-uk.

**Comment by ghaiklor** [comment]
@Trott could you add @denysdovhan to NodeJS organization? So I can make him a contributor to nodejs-uk.

**Comment by RReverser** [comment]
@ghaiklor Can't you add him individually?

**Comment by ghaiklor** [comment]
@RReverser unfortunately, no. I don't have rights to do this.

**Comment by Trott** [comment]
@ghaiklor Done.

**Comment by denysdovhan** [comment]
@Trott confirmed
