### ISSUE TITLE
Переклад nodejs чи iojs?

### ISSUE THREAD

**Issue by denysdovhan** [iojs/iojs-uk#83]
Я не до кінця розумію чи ми перекладаємо вже оновлену документацію node4 і вище, чи все таки iojs. Зважаючи на те, що переклад просунувся не сильно, можливо варто перекладати документацію nodejs?

Може хтось пояснити стан справ?

**Comment by ghaiklor** [comment]
@denysdovhan в то время еще был iojs, но я полностью поддерживаю тот факт, что его уже нету. Поэтому да, нужно начинать с nodejs.
