### ISSUE TITLE
nodejs-uk - United Kingdom , nodejs-ua - Ukraine

### ISSUE THREAD

**Issue by maksymseleznov** [iojs/iojs-uk#85]
чому UK?

**Comment by RReverser** [comment]
Залежить чи скорочення мови чи країни.

**Comment by ghaiklor** [comment]
@maksymseleznov http://lh.2xlibre.net/locale/uk_UA/ это страна, а не локализация.

**Comment by denysdovhan** [comment]
`uk` — це ISO–код української мови. Для англійської це `en`.
