### ISSUE TITLE
Broken layout on the site

### ISSUE THREAD

**Issue by denysdovhan** [iojs/iojs-uk#88]
![image](https://cloud.githubusercontent.com/assets/3459374/17361319/9f0b71fc-5978-11e6-81d8-b198d524955c.png)

We have broken layout on the site.

@RReverser has already checked that `Документація` won't break layout and everything was going to be okay. But something happened. I suppose this problem was caused by font which probably doesn't support cyrillic characters.

What do we have to do with that? I think the easiest way is removing `Документація` word from this blocks.

cc @nodejs/nodejs-uk

**Comment by denysdovhan** [comment]
Also we have mistake in 'Рекомендовано', but I'm already working on that.

**Comment by RReverser** [comment]
I would rather remove "API" (that one is more obvious) if possible.

**Comment by RReverser** [comment]
Btw, it's not really "broken", it's just normal responsive behavior of the website. Even with less text, it will show sometimes in a column and not a row on non-wide screens.

**Comment by denysdovhan** [comment]
On my MacBook 13" it is in a column, which is different to behavior on other languages.

**Comment by denysdovhan** [comment]
@nodejs/nodejs-uk I'm gonna remove “API”.
