### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by ghaiklor** [iojs/iojs-uk#9]
@sejoker Need to discuss the repository structure and how we will storing all the translations. My proposal is:

`website/uk` folder for storing iojs website translation.
`articles/` folder for storing translated articles for dou.ua or any else.
`weekly` folder maybe for some blogs, etc...

**Comment by sejoker** [comment]
я пропоную структуру с 1 рівнєм вкаденості :
- website/
- weekly/
- api/

**Comment by vladmiller** [comment]
Is there any recommendations from iojs team of how to structure your repos?

**Comment by sejoker** [comment]
@vladmiller  not much: https://github.com/iojs/website/blob/master/TRANSLATION.md.

**Comment by sejoker** [comment]
How I understand its up to us how we structure the repo

**Comment by vladmiller** [comment]
@sejoker I thought they want to build documentation which will automatically translate to all available languages. 
Well, I'll start adding translations to website/api/ folder and start from events.md. Does this sounds good?

**Comment by ghaiklor** [comment]
@vladmiller, @sejoker is right. We can decide how to structure our repo on our own. So our proposal was and still... 3 folders:
- `website` - for website translation;
- `weekly` - for weekly translations;
- `doc` - for documentation

**Comment by vladmiller** [comment]
@ghaiklor looks like in some other packages they adopt the similar structure.

**Comment by ghaiklor** [comment]
Finally we have structure.

In `master` branch we have:
- `doc` - folder where API documentation is located;
- `website` - folder where located content from website repo (content, wg-meetings, etc);
- `weekly` - folder for weekly news;

In `gh-pages` branch we have Ukrainian website for iojs.org.
