### ISSUE TITLE
Request translation for 2018 Node.js User survey promo copy

### ISSUE THREAD

**Issue by hackygolucky** [iojs/iojs-uk#92]
Hi! We'll be releasing the 2018 Node.js User Survey, and we'd love to have some promo copy in native languages to encourage our community users to participate. 

Requested copy to translate:
> Please take a few minutes to complete the 3rd annual Node.js User Survey, from the Node.js Foundation. Your participation helps us tell the story of Node.js and also informs Node.js Foundation strategy to ensure we invest in the right programs and resources to continue advancing Node.js. The results will be made public (find the most recent survey report here).
> 
> Thank you!

Thanks from the Node.js Foundation team!

**Comment by korzhyk** [comment]
> Будь ласка, приділіть декілька хвилин свого часу на проходження третього щорічного опитування користувачів Node.js від Node.js Foundation. Ваша участь допоможе нам творити історію Node.js, а також дозволить Node.js Foundation обирати правильні напрямки інвестування у програми та ресурси для подальшого розвитку Node.js. Результати будуть оприлюднені незабаром (переглянути результати останнього опитування можна тут).
> 
> Дякуємо!

This initial version, so we need some voices for approve this version.

**Comment by RReverser** [comment]
@korzhyk Looks great to me.

**Comment by hackygolucky** [comment]
Awesome, thanks so much!
